server:
  port: 8082
  context-path: /bgroot
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_fb
    username: root
    password: root
    thymeleaf:
        mode: HTML5
        encoding: UTF-8
        cache: false